version: '3.4'

services:
  client:
    image: eccdssbis24codechallenge-front
    build:
      context: ./client
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: development
      DOCKER_ENV: "true"
    ports:
      - 3000:3000
    volumes:
      - ./client:/app

  server:
    image: eccdssbis24codechallenge-back
    build:
      context: ./server
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 8080:8080
    volumes:
      - ./server:/app