version: '3.4'

services:
  client:
    image: eccdssbis24codechallenge-front
    build:
      context: ./client
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: development
      DOCKER_ENV: "true"
      VITE_API_URL: /api
    ports:
      - 3000:3000
    volumes:
      - ./client:/app

  server:
    image: eccdssbis24codechallenge-back
    build:
      context: ./server
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
      DOCKER_ENV: "true"
      CLIENT_URL: http://localhost:3000
      LOCATION_URL: https://api.github.com/users/bcgov/repos
      PORT: 8080
    ports:
      - 8080:8080
    volumes:
      - ./server:/app